name: Deployment pipeline

on:
  push:
    branch:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: npm install 
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build 
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
          browser: chrome
      - name: heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: fullstackopen-pokedex-101
          heroku_email: utkryuk@gmail.com
          healthcheck: "https://fullstackopen-pokedex-101.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true